services:
  - type: web
    name: gem-bot
    env: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: python -m src.bot.main 
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gemdb
          property: connectionString
