global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'gem-bot'
    static_configs:
      - targets: ['bot:8000']
    metrics_path: '/metrics'

  - job_name: 'postgres'
    static_configs:
      - targets: ['db:9187']
