version: '3.8'

services:
  bot:
    build: .
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - ADMIN_CHAT_ID=${ADMIN_CHAT_ID}
      - DATABASE_URL=postgresql://gemadmin:${DB_PASSWORD}@db:5432/gemdb
    depends_on:
      - db
    networks:
      - gem-network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: gemadmin
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: gemdb
    volumes:
      - gem-data:/var/lib/postgresql/data
    networks:
      - gem-network

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - gem-network

volumes:
  gem-data:

networks:
  gem-network:
