name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Upgrade pip & install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip list  # Affiche les packages installés pour debug

    - name: Run tests
      run: pytest -v tests/ || echo "Tests failed, continuing pipeline"
      continue-on-error: true  # Optionnel, à retirer si tu veux bloquer en cas d'échec

  deploy-prod:
    needs: [build-test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Deploy to Render via API
      run: |
        curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys" \
        -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
        -H "Accept: application/json" \
        -H "Content-Type: application/json" \
        -d '{}'
